### ISSUE TITLE
Schema UML

### ISSUE THREAD

**Issue by az4aaz** [Naiizey/Loppu#10]

**Comment by gablaxy** [comment]
can this issue be closed ?

**Comment by az4aaz** [comment]
Team, can you bring me feedback on this one ?
![UML](https://github.com/Naiizey/Loppu/assets/42306217/54e0a2c7-eaf3-463d-a8f4-132596fe8657)

**Comment by gablaxy** [comment]
@Mathis-Aubry @Sc2Marines @Naiizey

**Comment by Sc2Marines** [comment]
good changes!

**Comment by az4aaz** [comment]
Thank you, we consider this issue as closed !
